run:
  # This is where the performers should run.  If not "localhost" they will be scp-ed to here, in the form of a tarred Docker image.
  performer_server: localhost

database:
  # Generally only CI should be talking to production database.  For local performance testing, spin up a localhost database.
  hostname: localhost
  port: 5432
  username: postgres
  password: postgres

executables:
  curl:
  cbdyncluster: d:\dev\Couchbase\cbdyncluster-windows.exe --config d:\dev\Couchbase\.cbdyncluster.toml
  docker: C:\Program Files\Docker\Docker\resources\bin\docker.exe
